### ISSUE TITLE
Pattern Search and Examples

### ISSUE THREAD

**Issue by ollie** [manorie/textoken#7]
Hello there,

Would you mind creating a few real-world examples? I think they would give a good idea of what is possible with this library and how to design with it. I assume you are familiar with your field so this would help people (like me) who are interested in the topic but know pretty much zero about it.

Thanks,
Ollie

**Comment by thisiscetin** [comment]
Hello Ollie,

To give you an idea I am starting another project and this gem will be one of the basis components of it.
Assume that you have a text/article/rss feed, 100 sentences long. I will also use textoken to summarize it into 10 sentences. In this process I will start with options like - use more_than: 3 and exclude: 'numbers' . 
So in that way we will be able to reduce noise in the text. I am not sure which option values are gonna work better but as Textoken being a customizable library, I will have the ability to experiment many different combinations.

I am working on this kind of projects lately and I have found out that, whatever you do in AI and NLP field, tokenization is the starting point. If you make a mistake there, it doubles/triples.. at the higher levels. 
So this is gem will be a starting point of my experimental other projects. I have searched for Ruby libraries in the field and did not like them, because they are not customizable. 

Thanks for feedback, I will try to add some examples to readme file.

**Comment by ollie** [comment]
Sure. I was thinking more about an examples dir with some text file and corresponding script as it may clutter the readme or may be too short. Anyways, looking forward. :-)

**Comment by thisiscetin** [comment]
Good idea! . If you want, you are more than welcome to add examples to the project. I will add them if you don't have time to contribute, just let me know if you decide to start working on that. Thanks.

**Comment by ollie** [comment]
Yeah, that's the problem, I don't know how. The problem I have is I want to parse some information from some kind of .cfg file that contains obviously non-cfg stuff but has defined a structure, albeit weird one: https://gist.github.com/ollie/98cf38e7b30d5e226568

I could do it with regexes alone but I was thinking of a better approach like a descend parser but I didn't really like the libraries I found. It's a weird file, I don't know how the program parses it. :-)

**Comment by thisiscetin** [comment]
I will have a look at it and notify you.

**Comment by ollie** [comment]
I also updated the gist to include the script I currently use. I'm only interested in a handful of information and there is a lot of gibberish around.

**Comment by thisiscetin** [comment]
Probably we can solve this with some complex usage of textoken. But after looking through your doc, I think maybe I can add another option to gem.
For instance if you are interested in the text between TANK and END. You can give, (after implementation of this feature)

``` ruby
Textoken('The text inside file', pattern: { starts_with: 'TANK', ends_with: 'END' } ) 
```

So the response will be;

``` ruby
['POS', '0', '0', '0', 'SCALE', '25', '100', '25', .... ]
```

The index of first line ('POS') will be like 0, 16, 32 so it will be easy to classify writings line by line with a small method. The only downside of this implementation, you need to know the key at the starting block. In our case 'TANK', 'TRAIN2' and others..

So the usage can be,

``` ruby
['TANK', 'TRAIN2', 'LPAD1'...].each do |token|
     tokens = Textoken('text', pattern: { starts_with: token, ends_with: 'END' })
end
```

Does this kind of an approach helps you? 

I want to leave Textoken simple, because it needs to be fast and understandable. This is going to be a building block of many other things. But in your case and many other people's, having a pattern search like this can be helpful. You can also use Regexps in starts_with and ends_with. 

What do you think? @ollie

**Comment by ollie** [comment]
Hello, yeah I guess it could work. I'd need something else on top of that to rearrange the tokens, but that's just an implementation detail.
And yeah, keep it simple, if this pattern does not fit your use-case in mind, don't add it – I'm not even sure the gem should be dealing with this kind of thing.

Thanks though! :-)

**Comment by thisiscetin** [comment]
Yea it will make usage more complex, thanks for feedback closing the issue.
